#!/bin/bash


cd /usr/share/nova/Quasar

if (($# == 1)); then
	if [[ "$1" == "--debug" ]] || [[ "$1" == "-d" ]]; then
		echo "Debug mode: Running quasar without forever"
		NODE_PATH="/usr/share/nova/Quasar/build/Release:/usr/share/nova/Quasar/NodeNovaConfig/build/Release" node /usr/share/nova/Quasar/main.js
		exit
	else
		echo "Unknown arguement. Usage: quasar [-d (--debug)]"
		echo "  -d (--debug) Run node directly and show output in stdout instead of using forever to daemonize."
		exit
	fi
fi

echo "Starting quasar with the forever daemon"
NODE_PATH="/usr/share/nova/Quasar/build/Release:/usr/share/nova/Quasar/NodeNovaConfig/build/Release" forever start /usr/share/nova/Quasar/main.js
exit

