#!/bin/bash

cleanup()
{
	echo "Quitting debian package generation..."
	if [ -f Makefile.tmp ]
	then
		echo "Fixing Makefile..."
		rm -f Makefile
		mv Makefile.tmp Makefile
	fi
	echo "Finished"
	exit 0
}

set -e

trap cleanup SIGINT

#Assert root user
if [ $USER != "root" ]; then
	echo "Execute with root privileges: sudo $0"
	exit 1
fi

echo -e "Remember to update debian/changelog with current version and notes."

if [ -z $1 ]; then
	echo -e "Using default version number in version.txt..."
	VERSION=$(cat Installer/userFiles/config/version.txt)
else
	VERSION=$1
fi

PACKAGE="nova_$VERSION"

echo $PACKAGE

make clean

#cd into the directory where the script is
cd "$(dirname "$PACKAGE")"

# copy the files into a staging directory
rm -rf $PACKAGE
rm -f ../$PACKAGE.orig.tar.gz
mkdir $PACKAGE
cp -a $(ls -1 | grep -v $PACKAGE | grep -v "debian") $PACKAGE

#replace the Makefile with the debian version
cp debian/Makefile $PACKAGE
mv Makefile Makefile.tmp
cp debian/Makefile .

#tarball it up!
tar -zcf ../$PACKAGE.orig.tar.gz $PACKAGE

#remove the staging directory
rm -rf $PACKAGE

#Produce the debian package
dpkg-buildpackage -us -uc

# Use this to make a signed source package for the PPA
#debuild -S -k7F9F2E1F

#put the old makefile back in place
rm Makefile
mv Makefile.tmp Makefile

