#!/bin/bash


cd /usr/share/nova/NovaWeb

if (($# == 1)); then
	echo "$#"
	if [[ "$1" == "-debug" ]]; then
		echo "Debug mode: Running novaweb without forever"
		NODE_PATH="/usr/share/nova/NovaWeb/build/Release:/usr/share/nova/NovaWeb/NodeNovaConfig/build/Release" node /usr/share/nova/NovaWeb/main.js
		exit

	fi
fi

echo "Starting novaweb with the forever daemon"
NODE_PATH="/usr/share/nova/NovaWeb/build/Release:/usr/share/nova/NovaWeb/NodeNovaConfig/build/Release" forever start /usr/share/nova/NovaWeb/main.js
exit

