.TH LOCALTRAFFICMONITOR "1" "February 2012" "12.02"

.SH NAME
.B LocalTrafficMonitor 
\-  The Nova process that listens to traffic bound for the Nova host.

.SH SYNOPSIS
.B LocalTrafficMonitor

.SH DESCRIPTION
.PP
.I LocalTrafficMonitor 
Maintains suspect data from IPs that contact the host running Nova, and sends the evidence
to the Classification Engine to perform analysis and classify the suspects as either hostile
or benign.

.SH COPYRIGHT
.PP
Nova is Copyright (c) 2011 - 2012 DataSoft Corporation
.PP
Nova is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. Nova is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with Nova. If not, see <http://www.gnu.org/licenses/>.
