.TH NOVACLI "1" "February 2012" "12.02"

.SH NAME
.B novacli
\- The Nova command line interface

.SH SYNOPSIS
.B novacli

.SH DESCRIPTION
.PP
.I novacli
is the command line interface for controlling and communicating with the Nova daemon. The CLI has the ability to start and stop the haystack and the Nova daemon, and also has the ability to query it for status and state information. Run novacli with the --help option to display usage options.

.SH COPYRIGHT
.PP
Nova is Copyright (c) 2011 - 2012 DataSoft Corporation
.PP
Nova is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. Nova is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with Nova. If not, see <http://www.gnu.org/licenses/>.
