#!/bin/bash

TARGET=$1
FILE=/etc/rsyslog.d/40-nova.conf
NOT_IP=^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\:[0-9]{1,5}$

if [[ -z $TARGET ]]
then
{
  echo 'Usage: nova_rsyslog_helper TARGET_IP:TARGET_PORT'
  exit 1
}
fi
if [[ $TARGET =~ $NOT_IP ]]
then
{
  echo "Matched" >/dev/null
}
else
{
  echo "Invalid IP, aborting..."
  exit 1
}
fi

NEWCMND='if $programname == "novad" or $programname == "Nova" or $programname == "honeyd" then @@'

if grep -qs "$NEWCMND" $FILE
then
{
  sed -i "s|if.*$|$NEWCMND$TARGET|" $FILE
}
else
{
  echo $NEWCMND$TARGET >> $FILE
}
fi

sudo restart rsyslog
