#!/bin/bash

set -e

# Make sure we have root privs
if [[ $EUID -ne 0 ]]; then
   echo "You must be root to run this script. Aborting...";
   exit 1;
fi

# Add the user to the nova group
usermod -a -G nova $SUDO_USER

# Add /etc/sudoers.d to the sudoers file if needed
if grep -q "#includedir /etc/sudoers.d" /etc/sudoers; then
    echo "Note: sudoers.d is arleady included in /etc/sudoers"
else
    echo "No sudoers.d included in /etc/sudoers; attempting to add it";

    cp -f /etc/sudoers /tmp/sudoers.nova
    echo "#includedir /etc/sudoers.d" >> /tmp/sudoers.nova;

    if visudo -c -q -f /tmp/sudoers.nova; then
	echo "Saving changes to /etc/sudoers";
	cp -f /tmp/sudoers.nova /etc/sudoers;
    else
	echo "There was a problem with the sudoers file, aborting";
    fi

    rm -f /tmp/sudoers.nova
fi

QUERY="
CREATE TABLE firstrun(
	run TIMESTAMP PRIMARY KEY
);

CREATE TABLE credentials(
	user VARCHAR(100),
	pass VARCHAR(100)
);

CREATE TABLE suspect_alerts (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	suspect VARCHAR(40),
	timestamp TIMESTAMP,
	statistics INT,
	classification DOUBLE
);

CREATE TABLE statistics (
		id INTEGER PRIMARY KEY AUTOINCREMENT,

		ip_traffic_distribution DOUBLE,
		port_traffic_distribution DOUBLE,
		haystack_event_frequency DOUBLE,
		packet_size_mean DOUBLE,
		packet_size_deviation DOUBLE,
		distinct_ips DOUBLE,
		distinct_ports DOUBLE,
		packet_interval_mean DOUBLE,
		packet_interval_deviation DOUBLE,
		tcp_percent_syn DOUBLE,
		tcp_percent_fin DOUBLE,
		tcp_percent_rst DOUBLE,
		tcp_percent_synack DOUBLE,
		haystack_percent_contacted DOUBLE
);"

if [[ $1 == "reset" ]]; then
	echo "You chose the reset option. This will clear all database data!"
	rm -fr /usr/share/nova/database.db
fi



sqlite3 "/usr/share/nova/database.db" <<< $QUERY
sqlite3 "/usr/share/nova/database.db" <<< "INSERT INTO credentials VALUES('nova', '\$4\$nova\$h36yyW3noGPSWnx5JCalQCPoo74\$');"


echo "SQL schema has been set up for nova."
