#!/bin/bash

TARGET=$1
FILE=/home/$USER/Code/Nova/Installer/miscFiles/41-nova.conf
NOT_IP=^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\:[0-9]{1,5}$

if [[ -z $TARGET ]]
then
{
  echo 'Usage: nova_rsyslog_helper TARGET_IP:TARGET_PORT'
  exit 1
}
fi
if [[ $TARGET =~ $NOT_IP ]]
then
{
  echo "Matched" >/dev/null
}
else
{
  echo "Invalid IP, aborting..."
  exit 1
}
fi

if grep -qs $TARGET $FILE
then
{
  sed -i "s|@@.*$|@@$TARGET|g" $FILE
}
else
{
  sed -i "s|@@.*$|@@$TARGET|g" $FILE
}
fi

sudo cp $FILE /etc/rsyslog.d/

sudo restart rsyslog
