#!/bin/bash

set -e

# Make sure we have root privs
if [[ $EUID -ne 0 ]]; then
   echo "You must be root to run this script. Aborting...";
   exit 1;
fi

# Add the user to the nova group
usermod -a -G nova $SUDO_USER

# Add /etc/sudoers.d to the sudoers file if needed
if grep -q "#includedir /etc/sudoers.d" /etc/sudoers; then
    echo "Note: sudoers.d is arleady included in /etc/sudoers"
else
    echo "No sudoers.d included in /etc/sudoers; attempting to add it";

    cp -f /etc/sudoers /tmp/sudoers.nova
    echo "#includedir /etc/sudoers.d" >> /tmp/sudoers.nova;

    if visudo -c -q -f /tmp/sudoers.nova; then
	echo "Saving changes to /etc/sudoers";
	cp -f /tmp/sudoers.nova /etc/sudoers;
    else
	echo "There was a problem with the sudoers file, aborting";
    fi

    rm -f /tmp/sudoers.nova
fi


echo "Creating a new mysql user for NOVA. Please enter new password for user 'nova': "
read novapassword

DROP_QUERY="
DROP DATABASE nova;
DROP USER 'nova'@'localhost';
"

QUERY="
CREATE DATABASE nova;
USE nova;

CREATE USER 'nova'@'localhost' IDENTIFIED BY '$novapassword';
GRANT INSERT, SELECT, UPDATE, CREATE, DELETE, EXECUTE on nova.* to 'nova'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE credentials(
	user VARCHAR(100),
	pass VARCHAR(50)
) ENGINE=InnoDB;

CREATE TABLE suspect_alerts (
	id INT NOT NULL AUTO_INCREMENT,
	suspect VARCHAR(40),
	timestamp TIMESTAMP,
	statistics INT,
	classification DOUBLE,

	PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE statistics (
		id INT NOT NULL AUTO_INCREMENT,

		ip_traffic_distribution DOUBLE,
		port_traffic_distribution DOUBLE,
		haystack_event_frequency DOUBLE,
		packet_size_mean DOUBLE,
		packet_size_deviation DOUBLE,
		distinct_ips DOUBLE,
		distinct_ports DOUBLE,
		packet_interval_mean DOUBLE,
		packet_interval_deviation DOUBLE,
		tcp_percent_syn DOUBLE,
		tcp_percent_fin DOUBLE,
		tcp_percent_rst DOUBLE,
		tcp_percent_synack DOUBLE,
		haystack_percent_contacted DOUBLE,
	
		PRIMARY KEY(id)
) ENGINE=InnoDB;



INSERT INTO credentials VALUE('nova', SHA1('toor'));
"

echo "You will now be prompted for your MYSQL root password. This will not be saved and is only used once for creating an initial user and tables."
#/usr/bin/mysql --user=root -p <<< $DROP_QUERY
/usr/bin/mysql --user=root -p <<< $QUERY

echo "Mysql schema has been set up for nova."
