#!/bin/bash

set -e

#Set pcap permissions
setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip' /usr/bin/Novad
setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip' /usr/bin/honeyd

#make nova group
groupadd -f nova

#Make a honeyd log file folder that belongs to 'nobody'
chown -R nobody:nogroup /var/log/honeyd

# Make sure the UI_Core library gets found
ldconfig

#restart syslog so the changes will take effect
service rsyslog restart

#reload sysctl settings.
start procps

mkfifo /usr/share/nova/NovaMailPipe

chown ${SUDO_USER} /usr/share/nova/NovaMailPipe

#bash `pwd`/NovaCron ${SUDO_USER} 
