#!/bin/bash

set -e

#Set pcap permissions
setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip' /usr/bin/LocalTrafficMonitor
setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip' /usr/bin/Haystack
setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip' /usr/bin/honeyd
#Give permissions
chmod 0440 /etc/sudoers.d/sudoers_nova
#make nova group
groupadd -f nova
#Make a honeyd log file folder that belongs to 'nobody'
mkdir -p /var/log/honeyd
chown -R nobody:nogroup /var/log/honeyd
#add the file 40-nova.conf into /etc/rsyslog.d/
cp Installer/Read/40-nova.conf /etc/rsyslog.d/
#restart syslog so the changes will take effect
service rsyslog restart
