#!/bin/bash

set -e

#Set pcap permissions
setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip' /usr/bin/LocalTrafficMonitor
setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip' /usr/bin/Haystack
setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip' /usr/bin/honeyd
#make nova group
groupadd -f nova
#Make a honeyd log file folder that belongs to 'nobody'
chown -R nobody:nogroup /var/log/honeyd
#restart syslog so the changes will take effect
service rsyslog restart
