#!/bin/bash
rm -r /etc/nova
rm -r /usr/share/nova
rm -r $HOME/.nova
rm /usr/local/bin/NovaGUI
rm /usr/local/bin/ClassificationEngine
rm /usr/local/bin/DoppelgangerModule
rm /usr/local/bin/Haystack
rm /usr/local/bin/LocalTrafficMonitor
rm /etc/sudoers.d/sudoers_nova
rm -r .nova/Config
rm -r .nova/Data
rm -r bin
groupdel nova
echo "All Nova Components Removed"
